###########
# site.title

title:    'REALMAN'
subtitle: 'A proficient cliff detector -- from game to technology'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
